config/routes.rb
ConfigMep::Application.routes.draw do
  get "basic/index"
  get "basic/event"
  get "basic/content"
  get "basic/branding"
  get "basic/layout"
  get "basic/logistics"
  get "basic/app"

end

ConfigMep::Application.routes.draw do
  resources :orders
  resources :order_steps
    root to: 'orders#index'
  resources :events
  resources :event_steps 
    root to: 'events#index'

    root :to => "galleries#index"

  resources :galleries
  resources :paintings
  resources :components
  end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  
  # attr_accessible :title, :body
  # set_table_name("admin_users")

end

app/models/category.rb
class Category < ActiveRecord::Base 
  attr_accessible :category_id, :description, :name
  has_and_belongs_to_many :components
end

app/models/component.rb
class Component < ActiveRecord::Base 
  attr_accessible :gallery_id, :description, :name, :image
  belongs_to :gallery
  has_and_belongs_to_many :categories
  mount_uploader :image, ImageUploader
end

app/models/country.rb
class Country < ActiveRecord::Base
has_one :event
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :country
	attr_accessible :email, :rent_quantity, :rent_location, :rent_length,:wifi_setup,  :requirements, :firstname, :lastname, :phone_number


end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name
  has_many :paintings
end

app/models/order.rb
class Order < ActiveRecord::Base

def new
	# @picture = Picture.find(3)
end

def picture
# @picture = Picture.find(params[:id])
# send_data(@picture.data,
# filename: @picture.name,
# disposition: "inline")
end

def show
	# @picture = Picture.find(params[:id])

end



end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :name, :permalink, :visible, :position

  belongs_to :subject
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :gallery_id, :description, :name, :image
  belongs_to :gallery
  mount_uploader :image, ImageUploader
end

app/models/picture.rb
class Picture < ActiveRecord::Base

	attr_accessible :title, :description, :content_type, :binary_data, :path
end

app/models/section.rb
class Section < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :page
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :name, :visible, :position

  has_many :pages
end

app/controllers/basic_controller.rb
class BasicController < ApplicationController
  def index
  	@titre = "Welcome" 
  end 
  
  def event
  	@titre = "Your event"
  end 

  def content
  	@titre = "Content"
  end 

  def branding
  	@titre = "Branding"
  end 

  def layout
  	@titre = "Layout"
  end 

  def logistics
  	@titre = "Logistics"
  end 

  def app
  	@titre = "Your App"
  end 
end
 

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
  
    @gallery = Gallery.find(params[:id])
    @painting = Painting.where("gallery_id = ?", params[:id])
    respond_to do |format|
    	format.html
    	format.json { render json: @painting.as_json(only: [:id, :name])}
    end
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(params[:gallery])
    if @gallery.save
      flash[:notice] = "Successfully created gallery."
      redirect_to @gallery
    else
      render :action => 'new'
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update_attributes(params[:gallery])
      flash[:notice] = "Successfully updated gallery."
      redirect_to gallery_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    flash[:notice] = "Successfully destroyed gallery."
    redirect_to galleries_url
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_helper.rb
module BasicHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/event_steps_helper.rb
module EventStepsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/order_steps_helper.rb
module OrderStepsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/galleries/edit.html.erb
<% title "Edit Gallery" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @gallery %> |
  <%= link_to "View All", galleries_path %>
</p>

app/views/galleries/index.html.erb
<%= content_for :head do %>
<% for gallery in @galleries %>
  <div class="gallery">
    <h2><%= link_to gallery.name, gallery %></h2>
    Paintings: <%= gallery.paintings.size %>
  </div>
<% end %>

<p><%= link_to "New Gallery", new_gallery_path %></p>
<% end %>

app/views/galleries/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", galleries_path %></p>

app/views/galleries/show.html.erb
<%= content_for :head do %>
<h3>What are your needs ?</h3>
<div class="indication-text">We can advice a pre-configured package of applications based on your need. <br />Choose up to three packages on the list:</div>
<h5>2 optional remaining choices</h5>

  <% for painting in @gallery.paintings %>
  <div class="grid_9" id="row">
    <div class="grid_7" id="paintings">
      <div class="name"><h4><%= painting.name %></h4></div>
      <div class="description"><%= painting.description %></div>
      <div class="actions">
        <%= link_to "edit", edit_painting_path(painting) %> |
        <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>

    <div class="#" id="painting">
      <%= image_tag painting.image_url.to_s if painting.image? %>
    </div>
  </div>
  <% end %>
<div class="grid_4" id="links_galleries">
  <p>
  <%= link_to "Add a Painting", new_painting_path(:gallery_id => @gallery) %> |
  <%= link_to "Remove Gallery", @gallery, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View Galleries", galleries_path %>
</p>
</div>
  <div class="clear"></div>
</div>



<% end %>
 <%= params.inspect%>